#!/bin/bash

FILE='/etc/dse/cassandra/jvm.options'

echo "DROP KEYSPACE keyspace1;" | cqlsh
rm -rf /var/lib/cassandra/data/keyspace1*

cp /gc-labs/bash/conf/lab2/jvm.options /etc/dse/cassandra
cp /gc-labs/bash/conf/lab2/cassandra-env.sh /etc/dse/cassandra

shutdown -r now
