#!/bin/bash
#This needs to be placed in /usr/local/bin for execution
exercise=$1

if (( $EUID != 0 )); then
    echo "Please run as root"
    exit
fi

if [ $exercise = "lab1" ]; then
        `/home/automaton/.gc-labs/bash/jvm_changes/ex1`
elif [ $exercise = "lab2" ]; then
        `/home/automaton/.gc-labs/bash/jvm_changes/ex2`
elif [ $exercise = "ex3" ]; then
        `/home/automaton/.gc-labs/bash/jvm_changes/ex3`
elif [ $exercise = "ex4" ]; then
        `/home/automaton/.gc-labs/bash/jvm_changes/ex4`
elif [ $exercise = "ex5" ]; then
        `/home/automaton/.gc-labs/bash/jvm_changes/ex5`
elif [ $exercise = "ex6" ]; then
        `/home/automaton/.gc-labs/bash/jvm_changes/ex6`
fi	
