#!/bin/bash
#This needs to be placed in /usr/local/bin for execution
exercise=$1

if (( $EUID != 0 )); then
    echo "Please run as root"
    exit
fi

if [ $exercise = 2 ]; then
	`/gc-labs/bash/jvm_changes/ex2`
elif [ $exercise = 3 ]; then
	`/gc-labs/bash/jvm_changes/ex3`
elif [ $exercise = 4 ]; then
	`/gc-labs/bash/jvm_changes/ex4`
fi	
